### ISSUE TITLE
999 No error from Linkedin urls

### ISSUE THREAD

**Issue by Andersos** [gjtorikian/html-proofer#215]
I'm seeing some errors with `failed: 999 No error` from Linkedin urls [here](https://travis-ci.org/finn-no/tech.finn.no/builds/61735332#L187-L195).

After a curl I could see that Linkedin was sending `999 Request denied`

```Bash
Andersos$ curl -I https://no.linkedin.com/in/andersos

HTTP/1.1 999 Request denied
Date: Fri, 08 May 2015 09:08:21 GMT
X-Li-Pop: prod-lva1
X-LI-UUID: 2fAl5yE03BPgNe8APysAAA==
Content-Length: 956
Content-Type: text/html
```

According to [this](http://stackoverflow.com/questions/27231113/999-error-code-on-head-request-to-linkedin) question it looks like they are filtering on user agent. Is there anything that can be done, to get my tests to pass, other than ignoring the urls or removing links to Linkedin?

I'm using version [2.2.0](https://github.com/finn-no/tech.finn.no/blob/gh-pages/Gemfile.lock#L54).

**Comment by gjtorikian** [comment]
I just updated the README to note how the UA string can be changed. Good luck!

**Comment by Andersos** [comment]
Thanks, I ended up changing most of Linkedin urls and ignoring the rest.
I posted this so other people are able to search up this scenario.
Thanks for updating the README  :+1:

**Comment by jonbartlett** [comment]
I am having the same issue with LinkedIn urls. Changing the UA does not fix this for me. 

Strangely the test runs fine locally with or without the UA specified.
curl reports an error though locally.

Something to do with TravisCI?

**Comment by penibelst** [comment]
> Something to do with TravisCI?

What we see here is a result of [data wars](http://www.commitstrip.com/en/2015/05/19/data-wars/). We don’t know, what connections LinkedIn is blocking right now.

**Comment by vgaidarji** [comment]
I've faced the same issue and ignored `999` code for now:
```ruby
HTMLProofer.check_directory('./_site', http_status_ignore: [999]).run
```
