### ISSUE TITLE
Set enforce_https to false on the CLI

### ISSUE THREAD

**Issue by plaindocs** [gjtorikian/html-proofer#727]
From the 3->4 changelog 

> check_img_http was removed. All URLs are expected to be HTTPS; set enforce_https to false if you prefer keeping HTTP images around

Is that possible using the CLI? When using `--enforce-https=false` I get

```
/usr/local/share/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:33:in `go': needless argument: --enforce-https=false (OptionParser::NeedlessArgument)
	from /usr/local/share/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/local/share/gems/gems/html-proofer-4.0.1/bin/htmlproofer:11:in `<top (required)>'
	from /usr/local/bin/htmlproofer:25:in `load'
	from /usr/local/bin/htmlproofer:25:in `<main>'
```

**Comment by JackWilb** [comment]
Another note, this problem seems to also occur for `--check-external-hash=false`. Maybe this is a larger issue with boolean CLI parameters

**Comment by gjtorikian** [comment]
Whoops, thanks for the report. 4.1 should fix this.

**Comment by Atarity** [comment]
Still the same on 5.0.2 . In CLI below command was OK with 4.x.x
```
htmlproofer _site/ --extension .html --assume-extension .html --checks Links,Images,Scripts,OpenGraph --swap-attributes '{"img": [["src", "data-src"]] }' --enforce-https=false --ignore-status-codes 999,401 --disable-external=true --swap-urls www.mysite.com:localhost:4000
```

`--disable-external=true` also an issue.

**Comment by ModischFabrications** [comment]
Came here for the same error, might want to add something to the readme 😄

**Comment by gjtorikian** [comment]
5.x fixed this to make more logical sense and restore old behavior. Try 

```
--disable-external true
```

(In other words, no `=`.)

**Comment by Atarity** [comment]
I've tried this without `=` → `false does not exist (ArgumentError)`.

ruby 3.1.3, html-proofer 5.0.2

**Comment by gjtorikian** [comment]
Looking into it!

**Comment by gjtorikian** [comment]
Ah, I misread the original issue.

In 5.0, the commands changed:

* `--no-enforce-https`: this is equivalent to the old `enforce_https = false`
* `--disable-external`: this is equivalent to the old `disable-external = true`

This was done so that boolean expressions could use the `--[no-]*` syntax, which is common across Ruby CLI. Hope that helps!
